stages:
  - build_and_test
  - pages


variables:
  KATEX_VERSION: "0.13.9"


build_and_test:
  stage: build_and_test
  image: registry.gitlab.com/crypto_project/defi/infra/rust-solana:latest
  cache:
    key: target-1
    paths:
      - target
  artifacts:
    paths:
      - target/deploy/borrow_lending.so
      - target/idl/borrow_lending.json
      - target/types/borrow_lending.ts
      - target/release/cli
  before_script:
    - npm i
  script:
    - cargo test
    - ./bin/test.sh --token "${INFRA_API_TOKEN}"
    - cargo build --bin cli --release
    - ./target/release/cli help


# We generate docs.rs style documentation for the codebase and publish it as
# gitlab pages for the repository.
#
# This runs automatically on develop branch, or can be manually triggered on
# any other branch.
.pages_job:
  image: registry.gitlab.com/crypto_project/defi/infra/rust-solana:latest
  cache:
    key: pages-cache
    paths:
      - target
  artifacts:
    paths:
      - public
  script:
    - rustup override set nightly
    # generates docs.rs style page
    - cargo doc --lib --no-deps --document-private-items
    - cp -r target/doc public
    - cp -r docs public/docs

    # generates public index html file from README
    - node /scripts/prepareReadme.js |
      pandoc -t html --standalone --filter pandoc-katex
      --css "https://cdn.jsdelivr.net/npm/katex@${KATEX_VERSION}/dist/katex.min.css"
      --css https://pandoc.org/demo/pandoc.css
      --metadata title="Program borrow-lending"
      -o public/index.html

    # generates public index html file from README
    - cat CHANGELOG.md |
      pandoc -t html --standalone
      --metadata title="Borrow-lending program"
      -o public/changelog.html

    # generate code coverage report
    - cargo clean
    - ./bin/codecov.sh
    - cp -r target/debug/coverage public

# This job publishes pages to
# https://crypto_project.gitlab.io/defi/borrow-lending
pages:
  extends: .pages_job
  stage: pages
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# This job creates artifacts which can be browsed as static website, but does
# _not_ update https://crypto_project.gitlab.io/defi/borrow-lending
pages_manual:
  extends: .pages_job
  stage: pages
  when: manual
  except:
    - develop
