stages:
  - build_and_test
  - pages

variables:
  RUST_VERSION: "1.56.1"
  SOLANA_VERSION: "1.8.2"
  PANDOC_VERSION: "2.16.1"
  KATEX_VERSION: "0.13.9"

build_and_test:
  stage: build_and_test
  # https://hub.docker.com/r/cimg/rust/tags
  image: "cimg/rust:${RUST_VERSION}-node"
  cache:
    key: binaries-cache
    paths:
      - target
      # TODO: export the shmem program to another repo
      - tests/localnet-deps/target
  artifacts:
    # TODO: upon merging to develop or main, keep artifacts for ~6 months
    paths:
      - target/deploy/borrow_lending.so
      - target/idl/borrow_lending.json
  before_script:
    # TODO: export the solana CLI installation into a docker image in our own
    # registery
    - sh -c "$(curl -sSfL https://release.solana.com/v${SOLANA_VERSION}/install)"
    - export PATH="/home/circleci/.local/share/solana/install/active_release/bin:$PATH"

    - npm i
  script:
    - ./test.sh


pages:
  # We generate docs.rs style documentation for the codebase and publish it as
  # gitlab pages for the repository. This only happens on merge to develop
  # branch.
  stage: pages
  image: "cimg/rust:${RUST_VERSION}-node"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  before_script:
    - wget "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-1-amd64.deb"
    - sudo dpkg -i "pandoc-${PANDOC_VERSION}-1-amd64.deb"
    - cargo install pandoc-katex
  script:
    - cargo doc --lib --no-deps
    - cp -r target/doc public
    # generates public index html file from README
    - node bin/prepareReadme.js |
      pandoc -t html --standalone --filter pandoc-katex
      --css "https://cdn.jsdelivr.net/npm/katex@${KATEX_VERSION}/dist/katex.min.css"
      --css https://pandoc.org/demo/pandoc.css
      --metadata title="Program borrow-lending"
      -o public/index.html
