[programs.localnet]
borrow_lending = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tests/localnet-keypair.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/src/**/*.ts"
