[programs.localnet]
borrow_lending = "7vRDzPZK2toUCkGUgtb1uPZLXvtj8YvXUKUBRh8Ufr5y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "tests/localnet-keypair.json"

[scripts]
test = "ts-mocha --bail -p ./tsconfig.json -t 1000000 tests/src/**/*.ts"
