[package]
name = "cli"
version = "0.1.0"
edition = "2018"

[dependencies]
anchor-client = "0.18"
borrow-lending = { path = "../programs/borrow-lending", features = ["no-entrypoint"] }
clap = "3.0.0-beta.5"
dotenv = "0.15"
solana-sdk = "1.7"
