[package]
name = "cli"
version = "3.1.0"
edition = "2018"

[dependencies]
anchor-client = "0.21"
anchor-spl = "0.21"
clap = "3.0.0-beta.5"
dotenv = "0.15"
solana-sdk = "1.7"
serde_json = "1.0"

[dependencies.borrow-lending]
path = "../programs/borrow-lending"
features = ["no-entrypoint", "serde"]

